services:
  # Auth API - Go service
  auth-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET=PRFT
      - AUTH_API_PORT=8000
      - USERS_API_ADDRESS=http://users-api:8083
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge